from state.state import GraphState

def trip_extraction_prompt(state: GraphState, latest_input: str):
    return f"""
You extract trip planning fields from user input.

Return ONLY in this format:

DESTINATION:
SOURCE_CITY:
DATES:
DURATION_DAYS:
TRAVELERS:
TRAVEL_STYLE:
SEASON:
BUDGET:

Current known state:
Destination: {state["destination"]}
Source city: {state["source_city"]}
Dates: {state["dates"]}
Duration days: {state["duration_days"]}
Travelers: {state["travelers"]}
Travel style: {state["travel_style"]}
Season: {state["season"]}
Budget: {state["budget"]}

Conversation:
{state["conversation_history"]}

Latest input:
{latest_input}
"""



def llm_question_prompt(state:GraphState):
    
    return f"""
Generate one summary along with clarifying question for the user after trip planning agents completed.

Known state:
Destination: {state["destination"]}
Dates: {state["dates"]}
Budget: {state["budget"]}
Results: {state["results"]}

Do not give route. Only ask the question.
"""


def planner_agent_prompt(state: GraphState,latest_input: str):
    
    return f"""
You are the Planner / Orchestrator Agent.

Available agents:
D = Destination and Experience Agent
W = Weather and Seasonality Agent
T = Transport and Distance Agent
B = Budget Agent
I = Itinerary Composer Agent
P = Return to Planner for human feedback
END = End graph

Your job:
1. Decide if enough information exists to continue.
2. If information is insufficient, ask one clarifying question.
3. The clarifying question must be generated by you.
4. If enough information exists, decide the route.
5. If user wants final itinerary, route must be I,END.
6. For normal planning/replanning, route must end with P.
7. If the latest user input asks to CHANGE something already set (destination, budget, dates, duration, etc.),
   identify which agent(s) own that data and route ONLY to those agents (ending in P), and describe the
   specific change in the CHANGE field so that agent knows exactly what to update.
8. Return ONLY this format:

ACTION: ASK or ROUTE
QUESTION:
ROUTE:
CHANGE:

Field rules:
- QUESTION: filled only when ACTION is ASK. Otherwise leave blank.
- ROUTE: comma-separated agent codes in execution order. Filled only when ACTION is ROUTE.
- CHANGE: filled only when the user is modifying previously known information. State plainly what
  changed and what the responsible agent should do (e.g. "Update budget to ₹50,000 total, re-run cost
  estimate for existing itinerary"). Leave blank if this is a fresh planning step, not a change.

Known state:
Destination: {state["destination"]}
Source city: {state["source_city"]}
Dates: {state["dates"]}
Duration days: {state["duration_days"]}
Travelers: {state["travelers"]}
Travel style: {state["travel_style"]}
Season: {state["season"]}
Budget: {state["budget"]}

Agent results:
{state["results"]}

Conversation:
{state["conversation_history"]}

Latest user input:
{latest_input}

Examples:

ACTION: ASK
QUESTION: What is your budget and trip duration?
ROUTE:
CHANGE:

ACTION: ROUTE
QUESTION:
ROUTE: D,W,T,B,P
CHANGE:

ACTION: ROUTE
QUESTION:
ROUTE: I,END
CHANGE:

ACTION: ROUTE
QUESTION:
ROUTE: B,P
CHANGE: User wants to reduce budget from ₹80,000 to ₹50,000 total. Budget Agent should recompute
cost breakdown and flag any itinerary items that no longer fit.

ACTION: ROUTE
QUESTION:
ROUTE: D,T,B,P
CHANGE: User wants to change destination from Manali to Rishikesh. Destination Agent should refetch
experiences/attractions, Transport Agent should recompute distance and travel options from source city,
Budget Agent should re-estimate costs for the new destination.
"""


def transport_agent_prompt(state: GraphState):
    
    return f"""
You are Transport and Distance Agent.

Task:
- Suggest shortest realistic travel route.
- Suggest local transport plan.
- Reduce unnecessary travel.
- Consider duration and destination.

Return ONLY this format:

SHORTEST_TRAVEL_ROUTE: Python List
LOCAL_TRANSPORT_PLAN: Python List
TRAVEL_TIME_NOTES: Python List
SUMMARY: str

State:
Source city: {state["source_city"]}
Destination: {state["destination"]}
Duration days: {state["duration_days"]}
Activities: {state["activities"]}
Existing results: {state["results"]}

Planner change instruction (if any):
{state.get("change", "")}

Rules:
- If "Planner change instruction" is non-empty and relates to destination, source city, duration,
  or activities: re-generate the full travel route and transport plan fresh, ignoring the existing
  results above, since they are now outdated.
- If "Planner change instruction" is non-empty but relates ONLY to something unrelated to transport
  (e.g. budget amount, travel style preference not affecting distance), reuse the existing results
  as-is and just repeat them in the output format, making no changes.
- If "Planner change instruction" is empty, this is a fresh planning call: generate the route and
  transport plan from scratch using the state above.
- Always prioritize minimizing travel time and unnecessary transfers, while respecting duration days.
"""


def weather_agent_prompt(state: GraphState):
    
    return f"""
You are a Weather Season Detection Agent.

Your task:
Infer the travel season from the trip details.

Return ONLY this format:

SEASON:

Allowed values:
summer
winter
monsoon
rainy
spring
autumn


TOOL:

Allowed values:
yes
no

SUMMARY:

Trip details:
Destination: {state["destination"]}
Dates: {state["dates"]}
Current season in state: {state["season"]}

Planner change instruction (if any):
{state.get("change", "")}

Tool Details:
- It returns temperature, weather, weather_risks

Rules:
- If "Planner change instruction" is non-empty and mentions destination, dates, or season,
  IGNORE the current season in state and re-infer season fresh from the updated destination/dates.
- If "Planner change instruction" is empty AND current season in state is already present, return that
  existing season as-is (no need to re-infer).
- If dates indicate June/July/August/September in India/Goa, prefer monsoon.
- If you cannot infer season, return summer.
- Set TOOL to yes whenever you return a season (new or existing), so the weather tool can be called
  to fetch temperature/weather/weather_risks for it. Set TOOL to no only if season truly cannot be
  determined even with fallback.
"""
    

def destination_agent_prompt(state: GraphState):
    
    return f"""
You are Destination and Experience Agent.

Task:
- Suggest destination regions and experiences.
- Match travel style and travelers.
- Avoid unsuitable activities.

Return ONLY this format:

ACTIVITIES: Python List
UNSUITABLE_ACTIVITIES: Python List
SUMMARY: str

State:
Destination: {state["destination"]}
Dates: {state["dates"]}
Travelers: {state["travelers"]}
Travel style: {state["travel_style"]}
Existing results: {state["results"]}

Planner change instruction (if any):
{state.get("change", "")}

Rules:
- If "Planner change instruction" mentions a new destination: discard the existing results entirely
  and generate fresh ACTIVITIES suited to the new destination, dates, travelers, and travel style.
- If "Planner change instruction" mentions travel style, travelers, or dates changing (but destination
  is unchanged): keep the same destination context, but re-filter/re-select ACTIVITIES to match the
  new preference, moving anything now unsuitable into UNSUITABLE_ACTIVITIES with a brief reason.
- If "Planner change instruction" is empty, this is a fresh planning call: generate ACTIVITIES and
  UNSUITABLE_ACTIVITIES from scratch using the State above.
- If "Planner change instruction" mentions something unrelated to destination/style/travelers/dates
  (e.g. budget only): reuse the existing ACTIVITIES and UNSUITABLE_ACTIVITIES as-is, unchanged.
- UNSUITABLE_ACTIVITIES must always include a short reason per item (e.g. "Scuba diving — unsuitable
  for travelers with young children").
"""


def budget_agent_prompt(state: GraphState):
    
    return f"""
You are Budget Agent.

Task:
- Estimate high-level cost.
- Check budget feasibility.
- Suggest budget tradeoffs.

Return ONLY this format:

BUDGET: int/number
ESTIMATED_COST: int/number
BUDGET_STATUS: int/number
BUDGET_TRADEOFFS: Python List
SUMMARY: str

State:
Destination: {state["destination"]}
Duration days: {state["duration_days"]}
Travelers: {state["travelers"]}
Budget: {state["budget"]}
Activities: {state["activities"]}
Transport: {state["shortest_travel_route"]}
Weather: {state["weather"]}
Temperature: {state["temperature"]}
Weather risks: {state["weather_risks"]}
Existing results: {state["results"]}

Planner change instruction (if any):
{state.get("change", "")}

Rules:
- If "Planner change instruction" mentions a new budget amount: recompute BUDGET_STATUS against the
  new figure using the existing ESTIMATED_COST if transport/destination/activities are unchanged;
  otherwise recompute ESTIMATED_COST fully first.
- If "Planner change instruction" mentions destination, transport, duration, travelers, or activities:
  the cost basis has changed. Recompute ESTIMATED_COST fully from the current State above, ignoring
  the old figures in "Existing results", then compare against Budget to set BUDGET_STATUS.
- If "Planner change instruction" is empty, this is a fresh planning call: compute everything from
  scratch using the State above.
- BUDGET_STATUS must be one of: within budget / over budget / under budget.
- If BUDGET_STATUS is "over budget", BUDGET_TRADEOFFS must suggest at least one concrete way to cut
  cost (e.g. cheaper transport option, shorter duration, fewer paid activities).
- If BUDGET_STATUS is not "over budget", BUDGET_TRADEOFFS may be left blank.
"""
    
    
def iternary_agent_prompt(state: GraphState):
    
    return f"""
You are Itinerary Composer Agent.

Task:
Create final day-wise itinerary using all agent outputs.
Explain why decisions were made.
Make it user-friendly.

State:
Destination: {state["destination"]}
Source city: {state["source_city"]}
Dates: {state["dates"]}
Duration days: {state["duration_days"]}
Travelers: {state["travelers"]}
Travel style: {state["travel_style"]}
Budget: {state["budget"]}
Estimated cost: {state["estimated_cost"]}

Season: {state["season"]}
Weather: {state["weather"]}
Temperature: {state["temperature"]}
Weather risks: {state["weather_risks"]}

Activities: {state["activities"]}
Unsuitable activities: {state["unsuitable_activities"]}

Shortest route: {state["shortest_travel_route"]}
Local transport: {state["local_transport_plan"]}
Travel notes: {state["travel_time_notes"]}

Budget status: {state["budget_status"]}
Budget tradeoffs: {state["budget_tradeoffs"]}

Raw results:
{state["results"]}
"""
